const JP_TRANSLATIONS={
en:{
"nav.cart":"🛒 Cart",
"nav.cart.label":"Cart",
"hero.eyebrow":"Season 25/26 · Now Available",
"hero.title":"Premium Football Jerseys",
"hero.subtitle":"Club kits, national teams, and iconic retros — all in one place. Fast delivery, premium quality.",
"hero.cta.shop":"Shop Fan Edition",
"hero.cta.retros":"Explore Retros",
"hero.cta.find":"🔍 Can't find your jersey?",
"reviews.headline":"What our customers say",
"reviews.write":"✍️ Write a Review",
"search.placeholder":"Search jerseys — e.g. Liverpool, Argentina, Bayern...",
"search.results.title":"Search Results",
"search.noresults":"No jerseys found for",
"cat.fanedition":"🏟 Fan Edition",
"cat.national":"🌍 National Teams",
"cat.retroclubs":"🏆 Club Retros",
"cat.retronations":"🌐 Nation Retros",
"size.toggle":"📏 Size Guide ▾",
"size.size":"Size",
"size.height":"Height (cm)",
"size.chest":"Chest ½ (cm)",
"size.length":"Length (cm)",
"section.fe.tag":"Season 25/26",
"section.fe.title":"Fan Edition",
"section.fe.sub":"The latest club jerseys — home &amp; away, front &amp; back.",
"section.fe.more":"+ More clubs available — ask us →",
"banner.national":"🌍 Representing your nation",
"section.nt.tag":"World Cup 2026",
"section.nt.title":"National Teams",
"section.nt.sub":"Official jerseys for the biggest tournament in the world.",
"section.nt.more":"+ More nations available — ask us →",
"banner.retro":"🏆 Classics never go out of style",
"section.rc.title":"Club Classics",
"section.rc.sub":"Iconic jerseys from legendary seasons — front, back &amp; badge.",
"section.rc.more":"+ Many more retros available — ask us →",
"section.rn.title":"Nation Classics",
"section.rn.sub":"Relive iconic World Cup &amp; tournament moments.",
"section.rn.more":"+ More classic nations available — ask us →",
"mj.badge":"500+ Jerseys Available",
"mj.title":"Can't find your jersey?",
"mj.sub":"We stock hundreds more than what's listed here — including rare retros, full new-season club kits and all national team jerseys for World Cup 2026. Just tell us what you're looking for.",
"mj.btn":"Ask about a jersey →",
"mj.tag1":"🏆 Retro Classics",
"mj.tag2":"⚽ New Season 25/26",
"mj.tag3":"🌍 National Teams 2026",
"mj.tag4":"✏️ Custom Backprint",
"about.title":"About JerseyPhase",
"about.text":"At JerseyPhase we combine elite quality with clean design. No memberships. No hidden fees. Just your favorite team in premium fit.",
"contact.title":"Contact",
"contact.send":"Send us a message",
"contact.name.lbl":"Your Name *",
"contact.email.lbl":"Your Email *",
"contact.subject.lbl":"Subject *",
"contact.message.lbl":"Message *",
"contact.submit":"Send Message →",
"contact.success":"✅ Message sent! We'll get back to you shortly.",
"contact.error":"❌ Something went wrong. Please email us directly at jerseyphase@gmail.com",
"contact.name.ph":"e.g. Marco",
"contact.subject.ph":"e.g. Question about my order",
"contact.message.ph":"How can we help you?",
"footer":"© 2026 JerseyPhase. Built for modern football fans.",
"sticky.find":"🔍 Can't find your jersey?",
"review.title":"Write a Review",
"review.sub":"Reviews are verified against your order before publishing. Please enter the email address you used when ordering — we'll check it against our order list.",
"review.lbl.email":"Order Email *",
"review.lbl.name":"Your Name *",
"review.lbl.jersey":"Jersey ordered *",
"review.lbl.rating":"Rating *",
"review.lbl.text":"Your Review *",
"review.lbl.photo":"Photo (optional)",
"review.ph.email":"Email you used when ordering",
"review.ph.name":"e.g. Marco T.",
"review.ph.jersey":"e.g. Barcelona Home 25/26",
"review.ph.text":"Tell other customers about the quality, fit, delivery...",
"review.submit":"Submit Review →",
"review.note":"📋 Your review will be published after we verify your order (usually within 24h).",
"review.photo.btn":"📷 Add Photo",
"review.photo.none":"No file chosen",
"product.addtocart":"Add to cart — CHF",
"product.size":"Size",
"product.shorts":"+ Shorts",
"product.backprint":"+ Backprint (Name &amp; Nr.)",
"product.name.ph":"Player name (e.g. MÜLLER)",
"product.number.ph":"Number (e.g. 9)",
"product.viewmore":"View more",
"product.morejerseys":"more jerseys",
"cart.title":"Your Cart",
"cart.empty":"Your cart is empty.",
"cart.browse":"Browse jerseys",
"cart.subtotal":"Subtotal",
"cart.discount.ph":"Enter discount code…",
"cart.discount.apply":"Apply",
"cart.discount.remove":"Remove",
"cart.discount.ok":"✅ Code applied — {p}% discount!",
"cart.discount.err":"❌ Invalid discount code.",
"cart.discount.label":"🎉 Discount ({p}%)",
"cart.discount.label.10":"🎉 Discount (10%)",
"cart.total":"Total",
"cart.shipping":"🚚 <strong>Free Shipping</strong> — covered by JerseyPhase",
"cart.processing":"⏱️ <strong>Processing time:</strong> 2–5 days",
"cart.delivery":"📦 <strong>Delivery time:</strong> 7–14 days",
"checkout.title":"Shipping Details",
"checkout.sub":"No login required — we'll contact you to confirm your order.",
"checkout.name.lbl":"Full name *",
"checkout.email.lbl":"Email *",
"checkout.phone.lbl":"Phone number *",
"checkout.address.lbl":"Shipping address *",
"checkout.city.lbl":"City *",
"checkout.postal.lbl":"Postal code *",
"checkout.country.lbl":"Country *",
"checkout.notes.lbl":"Notes (optional)",
"checkout.card.lbl":"💳 Card Details *",
"checkout.submit":"Pay &amp; Place Order →",
"checkout.country.sel":"Select your country…",
"checkout.notes.ph":"Any special requests...",
"checkout.name.ph":"Your full name",
"checkout.phone.ph":"+41 79 123 45 67",
"checkout.address.ph":"Musterstrasse 12",
"checkout.city.ph":"Zürich",
"checkout.postal.ph":"8000",
"checkout.success":"✅ Payment successful! Your order has been placed.<br/><small>📧 Please check your <strong>Spam / Junk folder</strong> if you don't see our confirmation email in your inbox.</small>",
},
de:{
"nav.cart":"🛒 Warenkorb",
"nav.cart.label":"Warenkorb",
"hero.eyebrow":"Saison 25/26 · Jetzt verfügbar",
"hero.title":"Premium Fussballtrikots",
"hero.subtitle":"Clubtrikots, Nationalteams und ikonische Retros — alles an einem Ort. Schnelle Lieferung, Premium-Qualität.",
"hero.cta.shop":"Fan Edition shoppen",
"hero.cta.retros":"Retros entdecken",
"hero.cta.find":"🔍 Trikot nicht gefunden?",
"reviews.headline":"Was unsere Kunden sagen",
"reviews.write":"✍️ Bewertung schreiben",
"search.placeholder":"Trikots suchen — z.B. Liverpool, Argentinien, Bayern...",
"search.results.title":"Suchergebnisse",
"search.noresults":"Keine Trikots gefunden für",
"cat.fanedition":"🏟 Fan Edition",
"cat.national":"🌍 Nationalteams",
"cat.retroclubs":"🏆 Club Retros",
"cat.retronations":"🌐 Nations Retros",
"size.toggle":"📏 Größentabelle ▾",
"size.size":"Größe",
"size.height":"Grösse (cm)",
"size.chest":"Brust ½ (cm)",
"size.length":"Länge (cm)",
"section.fe.tag":"Saison 25/26",
"section.fe.title":"Fan Edition",
"section.fe.sub":"Die neuesten Clubtrikots — Heim &amp; Auswärts, Vorder- &amp; Rückseite.",
"section.fe.more":"+ Mehr Clubs verfügbar — frag uns →",
"banner.national":"🌍 Repräsentiere deine Nation",
"section.nt.tag":"Weltmeisterschaft 2026",
"section.nt.title":"Nationalteams",
"section.nt.sub":"Offizielle Trikots für das grösste Turnier der Welt.",
"section.nt.more":"+ Mehr Nationen verfügbar — frag uns →",
"banner.retro":"🏆 Klassiker kommen nie aus der Mode",
"section.rc.title":"Club Klassiker",
"section.rc.sub":"Ikonische Trikots aus legendären Saisons — Vorder-, Rückseite &amp; Logo.",
"section.rc.more":"+ Viele weitere Retros verfügbar — frag uns →",
"section.rn.title":"Nations Klassiker",
"section.rn.sub":"Erlebe ikonische WM- &amp; Turniermomente neu.",
"section.rn.more":"+ Mehr klassische Nationen verfügbar — frag uns →",
"mj.badge":"500+ Trikots verfügbar",
"mj.title":"Trikot nicht gefunden?",
"mj.sub":"Wir führen hunderte mehr als hier gelistet — darunter seltene Retros, neue Saison Clubtrikots und alle Nationalteam-Trikots für die WM 2026. Sag uns einfach, was du suchst.",
"mj.btn":"Nach einem Trikot fragen →",
"mj.tag1":"🏆 Retro Klassiker",
"mj.tag2":"⚽ Neue Saison 25/26",
"mj.tag3":"🌍 Nationalteams 2026",
"mj.tag4":"✏️ Custom Backprint",
"about.title":"Über JerseyPhase",
"about.text":"Bei JerseyPhase verbinden wir höchste Qualität mit clearem Design. Keine Mitgliedschaften. Keine versteckten Gebühren. Nur dein Lieblingsclub im Premium-Fit.",
"contact.title":"Kontakt",
"contact.send":"Schreib uns",
"contact.name.lbl":"Dein Name *",
"contact.email.lbl":"Deine E-Mail *",
"contact.subject.lbl":"Betreff *",
"contact.message.lbl":"Nachricht *",
"contact.submit":"Nachricht senden →",
"contact.success":"✅ Nachricht gesendet! Wir melden uns bald.",
"contact.error":"❌ Etwas ist schiefgelaufen. Schreib uns direkt: jerseyphase@gmail.com",
"contact.name.ph":"z.B. Marco",
"contact.subject.ph":"z.B. Frage zu meiner Bestellung",
"contact.message.ph":"Wie können wir dir helfen?",
"footer":"© 2026 JerseyPhase. Für moderne Fussballfans.",
"sticky.find":"🔍 Trikot nicht gefunden?",
"review.title":"Bewertung schreiben",
"review.sub":"Bewertungen werden vor der Veröffentlichung gegen deine Bestellung geprüft. Bitte gib die E-Mail-Adresse ein, die du beim Bestellen verwendet hast.",
"review.lbl.email":"Bestell-E-Mail *",
"review.lbl.name":"Dein Name *",
"review.lbl.jersey":"Bestelltes Trikot *",
"review.lbl.rating":"Bewertung *",
"review.lbl.text":"Deine Rezension *",
"review.lbl.photo":"Foto (optional)",
"review.ph.email":"E-Mail die du beim Bestellen verwendet hast",
"review.ph.name":"z.B. Marco T.",
"review.ph.jersey":"z.B. Barcelona Home 25/26",
"review.ph.text":"Erzähl anderen Kunden von der Qualität, Passform, Lieferung...",
"review.submit":"Bewertung absenden →",
"review.note":"📋 Deine Bewertung wird nach Überprüfung deiner Bestellung veröffentlicht (meistens innerhalb 24h).",
"review.photo.btn":"📷 Foto hinzufügen",
"review.photo.none":"Keine Datei ausgewählt",
"product.addtocart":"In den Warenkorb — CHF",
"product.size":"Grösse",
"product.shorts":"+ Shorts",
"product.backprint":"+ Backprint (Name &amp; Nr.)",
"product.name.ph":"Spielername (z.B. MÜLLER)",
"product.number.ph":"Nummer (z.B. 9)",
"product.viewmore":"Mehr anzeigen",
"product.morejerseys":"weitere Trikots",
"cart.title":"Dein Warenkorb",
"cart.empty":"Dein Warenkorb ist leer.",
"cart.browse":"Trikots ansehen",
"cart.subtotal":"Zwischensumme",
"cart.discount.ph":"Rabattcode eingeben…",
"cart.discount.apply":"Anwenden",
"cart.discount.remove":"Entfernen",
"cart.discount.ok":"✅ Code angewendet — {p}% Rabatt!",
"cart.discount.err":"❌ Ungültiger Rabattcode.",
"cart.discount.label":"🎉 Rabatt ({p}%)",
"cart.discount.label.10":"🎉 Rabatt (10%)",
"cart.total":"Gesamt",
"cart.shipping":"🚚 <strong>Gratis Versand</strong> — übernommen von JerseyPhase",
"cart.processing":"⏱️ <strong>Bearbeitungszeit:</strong> 2–5 Tage",
"cart.delivery":"📦 <strong>Lieferzeit:</strong> 7–14 Tage",
"checkout.title":"Lieferdetails",
"checkout.sub":"Keine Anmeldung nötig — wir kontaktieren dich zur Bestätigung.",
"checkout.name.lbl":"Vollständiger Name *",
"checkout.email.lbl":"E-Mail *",
"checkout.phone.lbl":"Telefonnummer *",
"checkout.address.lbl":"Lieferadresse *",
"checkout.city.lbl":"Stadt *",
"checkout.postal.lbl":"Postleitzahl *",
"checkout.country.lbl":"Land *",
"checkout.notes.lbl":"Anmerkungen (optional)",
"checkout.card.lbl":"💳 Kartendetails *",
"checkout.submit":"Bezahlen &amp; Bestellen →",
"checkout.country.sel":"Land auswählen…",
"checkout.notes.ph":"Besondere Wünsche...",
"checkout.name.ph":"Dein vollständiger Name",
"checkout.phone.ph":"+41 79 123 45 67",
"checkout.address.ph":"Musterstrasse 12",
"checkout.city.ph":"Zürich",
"checkout.postal.ph":"8000",
"checkout.success":"✅ Zahlung erfolgreich! Deine Bestellung wurde aufgegeben.<br/><small>📧 Bitte prüfe deinen <strong>Spam / Junk-Ordner</strong>, falls du unsere Bestätigungs-E-Mail nicht siehst.</small>",
}
};
let JP_LANG=localStorage.getItem("jp_lang")||"en";
function t(key,vars){
let str=JP_TRANSLATIONS[JP_LANG]?.[key]??JP_TRANSLATIONS.en?.[key]??key;
if(vars)Object.entries(vars).forEach(([k,v])=>{str=str.replaceAll(`{${k}}`,v);});
return str;
}
function applyTranslations(){
document.querySelectorAll("[data-i18n]").forEach(el=>{
const val=t(el.dataset.i18n);
if(val!==el.dataset.i18n)el.innerHTML=val;
});
document.querySelectorAll("[data-i18n-ph]").forEach(el=>{
el.placeholder=t(el.dataset.i18nPh);
});
document.querySelectorAll(".lang-btn").forEach(btn=>{
btn.classList.toggle("active",btn.dataset.lang===JP_LANG);
});
if(typeof renderProducts==="function")renderProducts();
if(typeof renderNationalTeams==="function")renderNationalTeams();
if(typeof renderRetros==="function")renderRetros();
if(typeof renderCart==="function"){renderCart();initDiscountUI();}
}
function setLang(lang){
JP_LANG=lang;
localStorage.setItem("jp_lang",lang);
applyTranslations();
}
document.addEventListener("DOMContentLoaded",()=>{
document.querySelectorAll(".lang-btn").forEach(btn=>{
btn.addEventListener("click",()=>setLang(btn.dataset.lang));
});
document.querySelectorAll(".lang-btn").forEach(btn=>{
btn.classList.toggle("active",btn.dataset.lang===JP_LANG);
});
applyTranslations();
});